import { Commands } from './Commands';

// list of cactus commands that are allowed to used by renderer process without confirmation via websocket - not dapp commands
const ALLOWED_COMMANDS_SET = new Set<keyof typeof Commands>([
  'daemon.register_service',
  'daemon.keyring_status',
  'daemon.get_version',
  'daemon.start_service',
  'daemon.stop_service',
  'daemon.set_label',
  'daemon.delete_label',
  'daemon.is_running',
  'daemon.get_keys',
  'daemon.get_key',
  'daemon.get_public_key',
  'daemon.get_wallet_addresses',
  'daemon.running_services',
  'daemon.get_plotters',
  'daemon.get_keys_for_plotting',
  'daemon.exit',
  'daemon.add_private_key',
  'daemon.unlock_keyring',
  'daemon.start_plotting',

  'cactus_wallet.ping',
  'cactus_full_node.ping',
  'cactus_farmer.ping',
  'cactus_harvester.ping',
  'cactus_data_layer.ping',

  'cactus_wallet.get_offer_summary',
  'cactus_wallet.get_network_info',
  'cactus_wallet.get_logged_in_fingerprint',
  'cactus_wallet.get_notifications',
  'cactus_wallet.get_sync_status',
  'cactus_wallet.get_wallets',
  'cactus_wallet.get_coin_records_by_names',
  'cactus_wallet.select_coins',
  'cactus_wallet.get_spendable_coins',
  'cactus_wallet.nft_get_wallet_did',
  'cactus_wallet.cat_get_asset_id',
  'cactus_wallet.cat_get_name',
  'cactus_wallet.cat_asset_id_to_name',
  'cactus_wallet.get_next_address',
  'cactus_wallet.get_cat_list',
  'cactus_wallet.get_stray_cats',
  'cactus_wallet.get_transaction_count',
  'cactus_wallet.get_transactions',
  'cactus_wallet.get_transaction',
  'cactus_wallet.get_wallet_balance',
  'cactus_wallet.get_wallet_balances',
  'cactus_wallet.get_current_derivation_index',
  'cactus_wallet.get_auto_claim',
  'cactus_wallet.nft_count_nfts',
  'cactus_wallet.nft_get_nfts',
  'cactus_wallet.nft_get_wallets_with_dids',
  'cactus_wallet.vc_get_list',
  'cactus_wallet.get_timestamp_for_height',
  'cactus_wallet.vc_get',
  'cactus_wallet.get_offers_count',
  'cactus_wallet.get_all_offers',
  'cactus_wallet.get_height_info',
  'cactus_wallet.get_puzzle_and_solution',
  'cactus_wallet.get_connections',
  'cactus_wallet.log_in',
  'cactus_wallet.generate_mnemonic',
  'cactus_wallet.check_delete_key',
  'cactus_wallet.cat_set_name',
  'cactus_wallet.verify_signature',
  'cactus_wallet.set_wallet_resync_on_startup',
  'cactus_wallet.delete_unconfirmed_transactions',
  'cactus_wallet.extend_derivation_index',
  'cactus_wallet.nft_get_info',
  'cactus_wallet.get_farmed_amount',

  'cactus_wallet.get_offer',
  'cactus_wallet.nft_calculate_royalties',
  'cactus_wallet.check_offer_validity',
  'cactus_wallet.get_transaction_memo',
  'cactus_wallet.pw_status',

  'cactus_wallet.did_get_did',
  'cactus_wallet.did_get_wallet_name',
  'cactus_wallet.did_set_wallet_name',
  'cactus_wallet.did_get_info',
  'cactus_wallet.did_find_lost_did',
  'cactus_wallet.did_get_current_coin_info',
  'cactus_wallet.did_get_information_needed_for_recovery',
  'cactus_wallet.did_get_metadata',
  'cactus_wallet.did_get_pubkey',
  'cactus_wallet.did_get_recovery_list',

  'cactus_wallet.vc_add_proofs',
  'cactus_wallet.vc_get_proofs_for_root',

  'cactus_full_node.get_unfinished_block_headers',
  'cactus_full_node.get_connections',
  'cactus_full_node.get_block_records',
  'cactus_full_node.get_block',
  'cactus_full_node.get_block_record',
  'cactus_full_node.get_blockchain_state',
  'cactus_full_node.get_fee_estimate',

  'cactus_farmer.get_harvesters_summary',
  'cactus_farmer.get_connections',
  'cactus_farmer.get_signage_points',
  'cactus_farmer.get_pool_state',
  'cactus_farmer.get_harvesters',
  'cactus_farmer.get_harvester_plots_duplicates',
  'cactus_farmer.get_harvester_plots_invalid',
  'cactus_farmer.get_harvester_plots_keys_missing',
  'cactus_farmer.get_harvester_plots_valid',
  'cactus_farmer.get_reward_targets',

  'cactus_harvester.get_harvester_config',
  'cactus_harvester.get_plot_directories',
  'cactus_harvester.refresh_plots',

  'cactus_data_layer.add_missing_files',
  'cactus_data_layer.check_plugins',
  'cactus_data_layer.clear_pending_roots',
  'cactus_data_layer.get_ancestors',
  'cactus_data_layer.get_keys',
  'cactus_data_layer.get_keys_values',
  'cactus_data_layer.get_kv_diff',
  'cactus_data_layer.get_local_root',
  'cactus_data_layer.get_mirrors',
  'cactus_data_layer.get_owned_stores',
  'cactus_data_layer.get_root',
  'cactus_data_layer.get_roots',
  'cactus_data_layer.get_root_history',
  'cactus_data_layer.get_sync_status',
  'cactus_data_layer.get_value',
  'cactus_data_layer.verify_offer',
  'cactus_data_layer.remove_subscriptions',
  'cactus_data_layer.subscribe',
  'cactus_data_layer.subscriptions',
  'cactus_data_layer.unsubscribe',
]);

export function isAllowedCommand(command: string): boolean {
  return ALLOWED_COMMANDS_SET.has(command);
}
